kotlin.code.style=official
# Java
klibs.java.source=8
klibs.java.target=11
klibs.java.ktarget=11
# Project
klibs.project.name=GradleFtpPlugin
klibs.project.group=ru.astrainteractive.ftpplugin
klibs.project.version.string=0.2.0
klibs.project.description=Gradle Ftp Plugin for file management
klibs.project.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
klibs.project.url=https://github.com/makeevrserg/GradleFtpPlugin
# Publish
klibs.publish.repo.name=GradleFtpPlugin
klibs.publish.groupId=ru.astrainteractive.ftpplugin
klibs.publish.description=Gradle Ftp Plugin for file management
klibs.publish.repo.org=makeevrserg
klibs.publish.name=GradleFtpPlugin
klibs.publish.license=Apache-2.0
klibs.publish.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
