[versions]
klibs-gradleplugin = "2.1.2"
kotlin-android-application = "9.2.1"
kotlin-dokka = "2.2.0"
kotlin-version = "2.3.21"
lint-detekt = "1.23.8"
ssh = "0.40.0"

[libraries]
android-toolsBuild = { module = "com.android.tools.build:gradle", version.ref = "kotlin-android-application" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "kotlin-dokka" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "kotlin-dokka" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin-dokka" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
lint-detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "lint-detekt" }
ssh = { module = "com.hierynomus:sshj", version.ref = "ssh" }

[plugins]
klibs-gradle-detekt = { id = "ru.astrainteractive.gradleplugin.detekt", version.ref = "klibs-gradleplugin" }
klibs-gradle-java-version = { id = "ru.astrainteractive.gradleplugin.java.version", version.ref = "klibs-gradleplugin" }
klibs-gradle-publication = { id = "ru.astrainteractive.gradleplugin.publication", version.ref = "klibs-gradleplugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
